- scripts/common_window.inc
- scripts/flax_beta.lua
Fixed issue with closing windows when growing flax seeds.
> closeAllWindows

- scripts/gather.lua
* Increased the tolerance on image clicks
> gather.lua

- scripts/common_window.inc
* Resolved random movement between passes.
> common_window.inc

- scripts/common_window.inc
Re-resolve random movement between passes.
> common_window

- scripts/flax_beta.lua
* Tolerance a little too high - minor reduction
> flax_beta.lua

- scripts/veg_janitor.lua
> veg_janitor

- scripts/gather_resources.lua
* dirt image fix
* switch logic around
> gather_resources.lua

- scripts/statclicks.lua
* Fixed window changing latency causing flaxComb to open an additional popup which could break the script.
> statclicks.lua

- scripts/statclicks.lua
* re-added weaving to statclicks
> statclicks.lua - weaving

- scripts/statclicks.lua
Fixed a failed check for consuming an onions in statclicks (weave, dig and flax comb)
> Failed check fix

- scripts/common_click.inc
> Stop drag() using an undefined global variable

- scripts/boards.lua
> boards.lua

- scripts/autorun.lua
* Re-enabled autoruns additional click functionality (foraging, shrooming and such...)
> autorun.lua

- scripts/common_window.inc
Added an optional parameter that will break out of the arranging loop if set.
> Update to arrangeStashed to limit number of windows

- scripts/acro_master.lua
* Switch AskAcro function from lsControlHeld  to lsAltHeld
> acro_master 

- scripts/acro_master.lua
* Switch 'Ask for Acro' key again, to shift, as Alt is used to lock the screen so that was a bad decision
> Better key for "ask to acro"

- scripts/fishing.lua
* A few minor fishing bug fixes
* Corrected the info text
> Minor bug fixes

- scripts/tubs.lua
* Fix missing image when steeping wool or canvas in clay
* Auto draw water when steeping wool or canvas in clay
> tubs.lua fix

- scripts/common_text.inc
> common_text.inc

- scripts/gather.lua
* fix the readSetting value for silt
> readSetting fix

- scripts/.luacheckrc
> luacheck additions

- scripts/statclicks.lua
* Fix consuming grilled veg when digging Limestone or Dirt using statclicks.lua
> Missing image search for consuming grilled veg

- scripts/autorun.lua
* Switch "Right click to stop" to "ESC to stop"
> kill right click to stop

- scripts/statclicks.lua
* Enabled Gun Powder
* Enabled Ink
> statclicks

- scripts/kiln.lua
* Handle popup checks more smoothly.
* Fix lint issues.
> Smoother checks

- scripts/cc_AutoExperimental.lua
- scripts/common_find.inc
- New charcoal script generates state when running that it uses to determine if a tick has happened. Takes no actions if no tick has occurred.
- Add new pixelMatch variations that use the screen buffer instead of reading from screen.
> Add new experimental charcoal automation script.

- scripts/fishing.lua
* Bug for indexing lure if already selected.
> Lure indexing

- scripts/glass.lua
* fixed all the lint errors.
* cleaned up the code.
* re-configured window boundries for better click accuracy.
> glass.lua boundry fix

- scripts/statclicks.lua
Better status message for user information.
> statclicks stashing info

- scripts/single_click_stat_mon.lua
Added constitution stat tracking
> singleclick - Added constitution image

- scripts/acronomicon.lua
* Stop spamming sound
* Display the timer, lost that in some changes
* Delay 7 seconds after following moves
> Fixes to Acronomicon

- scripts/vine_tender.lua
Wisdom was missed as a default vine option - fixed
> vine_tender - Added wisdom

- scripts/forge_auto.lua
typo / copy and paste error causing x1 Medium Gear to try and make x10
> Medium Gears - x1 typo fix

- scripts/tubs.lua
Squashed a performace bug causing the macro to freeze
> tubs - bug fix

- scripts/barley.lua
*Added auto water gathering.
*Tightened up the growth grid a little.
*Reduced total number of waterings by 1 when only using water.
> barley - Features & Tweaks

- scripts/blacksmithing.lua
- scripts/simon.lua
Also a small fix to blacksmithing troubleshooting mode.
> Add text/image clicking to simon, along with other smaller improvements.

- scripts/watermine.lua
Waits for Water Mine window to update after taking a gem.
> Added wait for server response

- scripts/watermine.lua
Gem count per pitch change was not resetting to 0. Now fixed.
Added ability to flip back and forth between known good pitch angles when gem yield slows on one.
Added additional help text at start of macro.
> Minor bug fix and added change pitch functionality

- scripts/common_find.inc
- scripts/dowses_with_ducks.lua
Also a small update to update dowse with ducks message
> Add utility window border color ranges

- scripts/watermine.lua
Added default change_pitch_time when it is nil.
> Bug fix for watermine

- scripts/mining_gems.lua
Minor gem mining fixes (pattern values and offsetting the refresh window click so it doesn't actually take the gems)
> Small gem mining fixes

- scripts/paper_press.lua
Changed num_loops to paper_passes
> Rename global variable

- scripts/kiln.lua
- scripts/statclicks.lua
* Added hotkey mode to kiln.lua
* Added a WindowManager call to kiln.lua
* Fixed a bug with weaving papy baskets in statclicks,lua
> kiln & statclicks

- scripts/drying_auto.lua
Additionally added WIndowManager and Unpin functionality
> Added sterile papyrus

- scripts/paint_by_numbers.lua
Macro currently overwrites an important file, user should be notified before continuing. This has been added.
> paintbynumbers - Added warning of file overwrite

- scripts/casting_items.txt
> castingitems - incorrect value

- scripts/cc_assist.lua
- scripts/common_window.inc
* Updated references to waterGap > uiGap
> waterGap > uiGap

- scripts/forge_auto.lua
- scripts/paint_by_numbers.lua
forge_auto.lua:
Bug fix - Changed CC add to findImage type
Feature - Added window manager with non-overlapping offsets
Feature - Added unpinOnExit functionality
> Updates for forge_auto.lua

- scripts/barley.lua
* Minor delay to stop issues with starting the following pass
> barley - minor delay

- scripts/woodTreatment.lua
> woodTreatment.lua - Cleanup

- scripts/kiln.lua
- scripts/statclicks.lua
- scripts/tubs.lua
> Minor Bugfixes

- scripts/stoneCutting.lua
> stoneCutting.lua - Added window manager

- scripts/thistle.lua
> thistle.lua - fix

- scripts/essences.lua
A first pass at porting the essence macro to T10, this will likely be buggy!
> Removed debugging

- scripts/essences.lua
> essences.lua

- scripts/essences.lua
Fix the temperature for Chicory
> essences.lua - temp fix

- scripts/treat_yo_self.lua
> treat_yo_self.lua

- scripts/metalTreatment.lua
> metalTreatment.lua

- scripts/crematory.lua
Fixed a bug causing the macro to not close detected popups and crash.
> crematory.lua

- scripts/crematory.lua
Fix the stupid popup issue with the crematory - finally!
> 3rd times a charm

- scripts/common_find.inc
- scripts/thistle.lua
Fix monitoring and cascading for upgraded thistle gardens
> thistle.lua

- scripts/common_click.inc
> drawWater - Storage Barrel

- scripts/chemistry/chem-cheap.txt
> chem-cheap - recipe fixes

- scripts/treat_yo_self.lua
Minor bug fix to correct the way purity tracking works when treating metal.
> treat_yo_self.lua - minor bug fixes

- scripts/statclicks.lua
New Script - Inspect spore papers based on focus timer
> Inspect Spore Papers

- scripts/bricks.lua
- scripts/common.inc
- scripts/distillationCoil.lua
- scripts/firepits.lua
- scripts/gather.lua
- scripts/incense_tracker.lua
- scripts/kiln.lua
- scripts/mining_gems.lua
- scripts/mining_ore.lua
- scripts/old_scripts/old_carpBlades.lua
- scripts/pottery.lua
- scripts/thermometer.lua
- scripts/tubs.lua
* Created a common string informing users about "locking" the chat window and updated all instances I can find to use that common text.
> Common "chat locked" message

- scripts/ancientforge_items.txt
- scripts/forge_auto.lua
* Added the Ancient Forge and Crawler parts to the macro.
* Added feature to automatically put the fire out when the queue of items to be made is empty.
> forge_auto.lua

- scripts/glass.lua
Remove previous fix.. Needs more testing
> revert glass.lua

- scripts/veg_janitor.lua
I was running into problems because I had tufts of grass enabled, so I've added it to the instructions.
> Improve veg-janitor instructions

- scripts/ToxinKitchen.lua
* Removed dead code for making Renenutet's Solvent
> Fix solvent production

- scripts/stoneCutting.lua
* MacPhisto's update to add hotkey support.
> Update stonecutting macro to handle hotkeys

- scripts/common_window.inc
- scripts/forge_auto.lua
Added in cascade window mode. 
Added auto take option
Added auto close (unpin) option 
Enhanced by allowing forges to shutdown when they have no more items to make rather than when all of them are complete
> Add cascading window support to forge_auto
